### ISSUE TITLE
No types defined for Typescript

### ISSUE THREAD

**Issue by erwinkulasic** [Fortnite-API/nodejs-wrapper#2]
Hello Fortnite API Team, This API has no declaration 
 (.d.ts) file. Would it be possible to add one?

Regards Erwin.
![Screenshot (1)](https://user-images.githubusercontent.com/30461767/103838145-a04d5c00-508c-11eb-92a1-298c3395fb85.png)

**Comment by ThisNils** [comment]
The package got renamed to [`fnapicom`](https://www.npmjs.com/package/fnapicom) and now contains type declarations.
